services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: delta_database
      MYSQL_USER: delta-service-account
      MYSQL_PASSWORD: password
    volumes:
      - ./src/main/java/data/create-database.sql:/docker-entrypoint-initdb.d/1-create-database.sql
      - ./src/main/java/data/seed-database.sql:/docker-entrypoint-initdb.d/2-seed-database.sql

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
